---

R1: # <-- locally significant name, although I specified device's actual hostname
    hostname: "192.168.60.160"
    groups:
        - cisco_group
    data:
        country: usa
        region: north
        state: newyork
        coast: east
        ip: "1.1.1.1 255.255.255.255"
        iBGP: True
        eigrp: 15


R2:
    hostname: "192.168.60.170"
    groups:
        - cisco_group
    data:
        country: usa
        region: north
        state: montana
        coast: west
        ip: "2.2.2.2 255.255.255.255"


R3:
    hostname: "192.168.60.180"
    groups:
        - cisco_group
    data:
        country: usa
        region: north
        state: virginia
        coast: east
        ip: "3.3.3.3 255.255.255.255"
        iBGP: True


R4:
    hostname: "192.168.60.190"
    groups:
        - cisco_group
    data:
        country: usa
        region: south
        state: texas
        coast: west
        ip: "4.4.4.4 255.255.255.255"
        iBGP: True


R5:
    hostname: "192.168.60.200"
    groups:
        - cisco_group
    data:
        country: usa
        region: south
        state: arizona
        coast: west
        ip: "5.5.5.5 255.255.255.255"
        eigrp: 15


R6:
    hostname: "192.168.60.210"
    groups:
        - cisco_group
    data:
        country: usa
        region: south
        state: florida
        coast: east
        ip: "6.6.6.6 255.255.255.255"
        iBGP: True


Mgmt-Switch:
    hostname: "192.168.60.150"
    groups:
        - Mgmt_group
    data:
        region: central

Switch-1:
    hostname: "192.168.60.220"
    groups:
        - Mgmt_group
    data:
        region: central
        tag: prod