---
- name: IOS Playbook to create Loopback
  hosts: ny
  gather_facts: no

  tasks:
    - name: Show interface
      cisco.ios.ios_command:
        commands: sho run interface g0/0
      register: vlan204

    - name: Display vlan204 variable
      debug:
        var: vlan204.stdout_lines[0]
